spiralsplash:
  spawns:
    - world: world
      x: 50.5
      y: 135.0
      z: 159.5
      yaw: 180.0
      pitch: 0.0
    - world: world
      x: 43.5
      y: 135.0
      z: 157.5
      yaw: -135.0
      pitch: 0.0
    - world: world
      x: 41.5
      y: 135.0
      z: 150.5
      yaw: -90.0
      pitch: 0.0
    - world: world
      x: 43.5
      y: 135.0
      z: 143.5
      yaw: -45.0
      pitch: 0.0
    - world: world
      x: 50.5
      y: 135.0
      z: 141.5
      yaw: 0.0
      pitch: 0.0
    - world: world
      x: 57.5
      y: 135.0
      z: 143.5
      yaw: 45.0
      pitch: 0.0
    - world: world
      x: 59.5
      y: 135.0
      z: 150.5
      yaw: 90.0
      pitch: 0.0
    - world: world
      x: 57.5
      y: 135.0
      z: 157.5
      yaw: 135.0
      pitch: 0.0
  colors:
    - RED_WOOL
    - ORANGE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PURPLE_WOOL
    - PINK_WOOL
    - LIGHT_GRAY_WOOL
    - GRAY_WOOL
  watercoords:
    pos1:
      world: world
      x: 44
      y: 72
      z: 144
    pos2:
      world: world
      x: 56
      y: 72
      z: 156
oceanparkour:
  checkpoints:
    - world: world
      x: 244.5
      y: 76.0
      z: 170.5
      yaw: 180.0
      pitch: 0.0
    - world: world
      x: 252.5
      y: 79.0
      z: 127.5
      yaw: 90.0
      pitch: 0.0
    - world: world
      x: 240.5
      y: 77.0
      z: 119.5
      yaw: 90.0
      pitch: 0.0
    - world: world
      x: 250.5
      y: 83.0
      z: 130.5
      yaw: 0.0
      pitch: 0.0
    - world: world
      x: 250.5
      y: 84.0
      z: 150.5
      yaw: 0.0
      pitch: 0.0

